FROM openjdk:8-jdk-alpine
LABEL Thiago Lopes da Silva <thiagoolsilva@gmail.com>
COPY build/libs/Goal-API-0.0.1-SNAPSHOT.jar Goal-API-0.0.1-SNAPSHOT.jar
ENTRYPOINT ["java","-jar","/Goal-API-0.0.1-SNAPSHOT.jar"]