version: "3.3"
services:
  goal-api:
    depends_on:
      - db
    container_name: goal-rest-api
    build:
      context: Goal-API
      dockerfile: Dockerfile
    image: goal-rest-api
    ports:
      - 8080:8080
    networks:
      - api-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/compose-postgres
      - SPRING_DATASOURCE_USERNAME=compose-postgres
      - SPRING_DATASOURCE_PASSWORD=compose-postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    image: 'postgres:13.2'
    container_name: db
    environment:
      - POSTGRES_USER=compose-postgres
      - POSTGRES_PASSWORD=compose-postgres
    networks:
      - api-network
networks:
    api-network:
        driver: bridge
